'rclone'

cask 'firefox'
cask 'visual-studio-code'
cask 'gimp'
cask 'vlc'
cask 'disk-inventory-x'

cask 'discord'
cask 'microsoft-office'
cask 'deluge'
cask 'balenaetcher'
cask 'grandperspective'
cask 'logitech-g-hub'
cask 'docker'
cask 'zoom'
cask '1kc-razer'
