brew 'packer'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'

cask 'firefox'
cask 'evernote'
cask 'atom'
cask 'gimp'
cask 'vlc'
cask 'sourcetree'
cask 'google-backup-and-sync'
cask 'disk-inventory-x'

cask 'slack'
cask 'microsoft-office'
cask 'mysqlworkbench'
cask 'nomad'
cask 'wireshark'

